const express = require("express");
const cors = require("cors");
require("dotenv").config();

const fs = require("fs/promises");
const path = require("path");

const { GoogleGenAI } = require("@google/genai");
const { tavily } = require("@tavily/core");

const app = express();

// ==========================================
// MIDDLEWARE
// ==========================================

app.use(cors());
app.use(express.json());

// ==========================================
// AI CLIENT
// ==========================================

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

// ==========================================
// SEARCH CLIENT
// ==========================================

const tvly = tavily({
  apiKey: process.env.TAVILY_API_KEY,
});

// ==========================================
// RESEARCH OUTPUT DIRECTORY
// ==========================================

const outputDirectory = path.join(__dirname, "research-output");

// ==========================================
// SAVE RESEARCH AS OBSIDIAN MARKDOWN
// ==========================================

async function saveResearchNote(topic, report, sources) {
  // Create research-output folder if it doesn't exist
  await fs.mkdir(outputDirectory, {
    recursive: true,
  });

  // Convert topic into a safe filename
  const safeTopic = topic
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();

  // Create timestamp
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");

  const filename = `${safeTopic}-${timestamp}.md`;

  const filePath = path.join(outputDirectory, filename);

  // Convert sources into Markdown links
  const sourceMarkdown = sources
    .map((source) => {
      return `- [${source.title}](${source.url})`;
    })
    .join("\n");

  // Create the Markdown document
  const markdown = `---
title: "${topic}"
created: "${new Date().toISOString()}"
type: research
tags:
  - research
  - ai-generated
---

# ${topic}

${report}

## Sources

${sourceMarkdown}

---

*Generated by Research Assistant*
`;

  // Write Markdown file
  await fs.writeFile(filePath, markdown, "utf8");

  console.log("\nObsidian note created:");
  console.log(filePath);

  return {
    filename: filename,
    filePath: filePath,
  };
}

// ==========================================
// TEST ROUTE
// ==========================================

app.get("/api/hello", (req, res) => {
  res.json({
    message: "Hello from my Express backend!",
  });
});

// ==========================================
// RESEARCH ROUTE
// ==========================================

app.post("/api/research", async (req, res) => {
  try {
    const topic = req.body.topic;

    // Validate input
    if (!topic) {
      return res.status(400).json({
        message: "Research topic is required.",
      });
    }

    console.log("\n================================");
    console.log("Research topic:", topic);
    console.log("================================");

    // ==========================================
    // STEP 1: SEARCH THE WEB
    // ==========================================

    console.log("\nSearching the web...");

    const searchResponse = await tvly.search(topic, {
      search_depth: "basic",

      max_results: 5,
    });

    console.log("Sources found:", searchResponse.results.length);

    // ==========================================
    // STEP 2: FORMAT SOURCES FOR GEMINI
    // ==========================================

    const sources = searchResponse.results
      .map((result, index) => {
        return `
SOURCE ${index + 1}

Title:
${result.title}

URL:
${result.url}

Content:
${result.content}
`;
      })
      .join("\n-------------------------\n");

    // ==========================================
    // STEP 3: CREATE GEMINI RESEARCH PROMPT
    // ==========================================

    const prompt = `
You are an evidence-based research assistant.

Research topic:
${topic}

Below are web sources retrieved specifically for this research.

${sources}

Using ONLY the information provided in these sources:

1. Give a concise overview.
2. Identify the most important findings.
3. Explain important developments or applications.
4. Explain why the topic matters.
5. Mention disagreements or limitations if the sources contain them.
6. Do not invent facts that are not supported by the sources.
7. Add source citations using [Source 1], [Source 2], etc.
8. End with a short conclusion.

Write a clear, structured research report using Markdown.
`;

    // ==========================================
    // STEP 4: GEMINI SYNTHESIS
    // ==========================================

    console.log("\nGenerating AI research...");

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",

      contents: prompt,
    });

    const report = response.text;

    console.log("AI research generated successfully.");

    // ==========================================
    // STEP 5: PREPARE SOURCE INFORMATION
    // ==========================================

    const sourcesForNote = searchResponse.results.map((result, index) => {
      return {
        id: index + 1,
        title: result.title,
        url: result.url,
      };
    });

    // ==========================================
    // STEP 6: CREATE OBSIDIAN NOTE
    // ==========================================

    const note = await saveResearchNote(topic, report, sourcesForNote);

    // ==========================================
    // STEP 7: SEND RESULT TO FRONTEND
    // ==========================================

    res.json({
      message: report,

      sources: sourcesForNote,

      note: {
        filename: note.filename,
      },
    });
  } catch (error) {
    console.error("\nResearch error:", error);

    res.status(500).json({
      message: "Research failed",

      error: error.message,
    });
  }
});

// ==========================================
// SERVE GENERATED OBSIDIAN FILES
// ==========================================

app.use("/research-output", express.static(outputDirectory));

// ==========================================
// START SERVER
// ==========================================

app.listen(3000, () => {
  console.log("Server running at http://localhost:3000");
});
